title: Archie Worth
description: My personal homepage 
theme: minima
email: archieworth7@gmail.com
github_username: ameworth

# Stylesheet rubbish 
sass:
  sass_dir: _sass
  style: compressed


# Optional: plugins (GitHub Pages supports a whitelist)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme